name: Test Pipeline

on:
  push:
    branches:
      - main  # Trigger on every push to the main branch

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Fetch only the latest commit

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Adjust based on your project requirements

      # Step 3: Verify the tests.sh file exists and is executable
      - name: Verify test.sh
        run: |
          echo "Checking if project/tests.sh file exists..."
          if [ ! -f ./project/tests.sh ]; then
            echo "Error: project/tests.sh not found!"
            exit 1
          fi
          echo "Making project/tests.sh executable..."
          chmod +x ./project/tests.sh

      # Step 4: Run the tests.sh script
      - name: Run tests
        run: |
          echo "Starting test script execution..."
          ./project/tests.sh
        shell: bash
